# Generated by Django 4.2.16 on 2026-09-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('curriculum', '0002_alter_lesson_xp_reward_alter_quiz_xp_reward_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_minutes', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapter')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('current_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_overview', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_progress_overviews',
            },
        ),
    ]
