# Generated by Django 4.2.16 on 2026-09-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(db_index=True)),
                ('subject_tag', models.CharField(default='General', max_length=100)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FORMAT_TEST', 'Content Format Test'), ('CODE_SNIPPET', 'Code Snippet Analysis'), ('LOGIC_PUZZLE', 'Logic / Algorithmic Puzzle'), ('INTEREST_RATING', 'Interest Self-Report / Mini-Task')], default='MCQ', max_length=30)),
                ('format_type', models.CharField(choices=[('text', 'Text Explanation'), ('visual_diagrams', 'Visual Diagrams'), ('interactive', 'Interactive Content'), ('animation', 'Animation'), ('audio_explanation', 'Audio Explanation'), ('practical_coding', 'Practical Coding'), ('none', 'Standard Assessment')], default='none', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('media_url', models.CharField(blank=True, max_length=300)),
                ('interactive_data', models.JSONField(blank=True, default=dict)),
                ('code_snippet', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('points', models.IntegerField(default=10)),
                ('difficulty', models.CharField(default='Beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('overall_score', models.FloatField(default=0.0)),
                ('ai_profile_generated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('selected_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=1)),
                ('points_earned', models.IntegerField(default=0)),
                ('self_reported_interest', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='assessments.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_attempts',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentContentFormatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('text', 'Text Explanation'), ('visual_diagrams', 'Visual Diagrams'), ('interactive', 'Interactive Content'), ('animation', 'Animation'), ('audio_explanation', 'Audio Explanation'), ('practical_coding', 'Practical Coding'), ('none', 'Standard Assessment')], max_length=30)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('engagement_time_seconds', models.IntegerField(default=0)),
                ('retention_score', models.FloatField(default=0.0)),
                ('effectiveness_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_results', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'student_content_format_results',
                'ordering': ['-effectiveness_score'],
                'unique_together': {('session', 'format_type')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_days',
                'ordering': ['session', 'day_number'],
                'unique_together': {('session', 'day_number')},
            },
        ),
    ]
