# Generated by Django 4.2.16 on 2026-09-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
        ('curriculum', '0002_alter_lesson_xp_reward_alter_quiz_xp_reward_chapter_and_more'),
        ('assessments', '0001_initial'),
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Personalized Computer Science Path', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personalized_learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapter')),
                ('coding_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.codingchallenge')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_engine.personalizedlearningpath')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'db_table': 'learning_path_items',
                'ordering': ['path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AIStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_summary', models.TextField()),
                ('recommended_starting_subject', models.CharField(default='Python', max_length=100)),
                ('recommended_difficulty', models.CharField(default='Beginner', max_length=50)),
                ('strengths', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('effective_learning_formats', models.JSONField(default=list)),
                ('programming_readiness_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('interest_areas', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('recommended_path', models.JSONField(default=list)),
                ('raw_llm_response', models.JSONField(blank=True, default=dict)),
                ('ai_provider', models.CharField(default='openai', max_length=50)),
                ('model_version', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_profiles', to='assessments.assessmentsession')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_student_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('suggested_changes', models.JSONField(default=dict)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
