# Generated by Django 4.2.16 on 2026-09-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('quiz_accuracy', models.FloatField(default=0.0)),
                ('coding_accuracy', models.FloatField(default=0.0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('challenges_solved', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'db_table': 'student_subject_performances',
                'ordering': ['-mastery_percentage'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentLearningMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_passed', models.IntegerField(default=0)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_learning_metrics',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
