# Generated by Django 4.2.16 on 2026-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(blank=True, default='Semester 1', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='educational_year',
            field=models.CharField(blank=True, default='Year 1', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programming_experience',
            field=models.CharField(blank=True, default='Beginner', max_length=50),
        ),
    ]
