# Generated by Django 4.2.16 on 2026-08-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness_score', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('efficiency_score', models.IntegerField(default=0)),
                ('best_practices_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('time_complexity', models.CharField(blank=True, max_length=50)),
                ('space_complexity', models.CharField(blank=True, max_length=50)),
                ('feedback', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('optimized_code', models.TextField(blank=True)),
                ('optimization_notes', models.TextField(blank=True)),
                ('original_complexity', models.CharField(blank=True, max_length=50)),
                ('optimized_complexity', models.CharField(blank=True, max_length=50)),
                ('ai_provider', models.CharField(default='heuristic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='coding.submission')),
            ],
            options={
                'db_table': 'code_analyses',
            },
        ),
    ]
