# Generated by Django 4.2.16 on 2026-08-31 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('banner_color', models.CharField(default='#6C63FF', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('xp_reward_1st', models.IntegerField(default=500)),
                ('xp_reward_2nd', models.IntegerField(default=300)),
                ('xp_reward_3rd', models.IntegerField(default=200)),
                ('xp_reward_participant', models.IntegerField(default=50)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=100)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codingchallenge')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='competitions.competition')),
            ],
            options={
                'db_table': 'competition_problems',
                'ordering': ['competition', 'order'],
                'unique_together': {('competition', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('problems_solved', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competition_participants',
                'ordering': ['competition', 'rank', '-score'],
                'unique_together': {('competition', 'student')},
            },
        ),
    ]
