# Generated by Django 4.2.16 on 2026-09-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('curriculum', '0002_alter_lesson_xp_reward_alter_quiz_xp_reward_chapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'number']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['chapter', 'order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='animation_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='animation_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visual_diagram_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='curriculum.level'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code_language',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.level'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='subjects.subject')),
            ],
            options={
                'db_table': 'curriculum_modules',
                'ordering': ['subject', 'order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='curriculum.module'),
        ),
    ]
