# Generated by Django 4.2.16 on 2026-08-31 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('badge_color', models.CharField(default='#FFD700', max_length=20)),
                ('condition_type', models.CharField(choices=[('TOTAL_XP', 'Total XP Reached'), ('CHALLENGES_COMPLETED', 'Challenges Completed'), ('QUIZZES_COMPLETED', 'Quizzes Completed'), ('LESSONS_COMPLETED', 'Lessons Completed'), ('STREAK_DAYS', 'Day Streak'), ('PERFECT_QUIZ', 'Perfect Quiz Score'), ('COMPETITION_WIN', 'Competition Win'), ('CODE_QUALITY', 'Code Quality Score'), ('FIRST_SUBMISSION', 'First Submission'), ('FIRST_QUIZ', 'First Quiz')], max_length=30)),
                ('condition_value', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎁', max_length=50)),
                ('reward_type', models.CharField(choices=[('HINT', 'Extra Hint'), ('EXTRA_ATTEMPT', 'Extra Attempt'), ('SPECIAL_CHALLENGE', 'Special Challenge'), ('AVATAR_ITEM', 'Avatar Item'), ('BADGE', 'Special Badge'), ('THEME', 'Theme Unlock')], max_length=20)),
                ('xp_cost', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['xp_cost'],
            },
        ),
        migrations.CreateModel(
            name='RewardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_spent', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='gamification.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source', models.CharField(choices=[('LESSON', 'Lesson Completed'), ('QUIZ', 'Quiz Passed'), ('CHALLENGE', 'Coding Challenge'), ('COMPETITION', 'Competition'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK', 'Daily Streak'), ('CODE_QUALITY', 'High Code Quality'), ('REWARD_SPENT', 'Reward Purchase'), ('MANUAL', 'Manual Award')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='xp_transact_student_42866b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='gamification.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
