# Generated by Django 4.2.16 on 2026-09-08 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LOGIC', 'Core Logic & Sequencing'), ('CONTROL_FLOW', 'Control Flow & Loops'), ('STATE', 'Variables & State'), ('MODULARITY', 'Functions & Modularity'), ('DATA_STRUCTURES', 'Data Structures & Collections'), ('ALGORITHMS', 'Algorithms & Optimization'), ('DEBUGGING', 'Debugging & Analysis')], default='LOGIC', max_length=30)),
                ('concept', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎮', max_length=50)),
                ('badge_color', models.CharField(default='#6366f1', max_length=30)),
                ('gradient', models.CharField(default='linear-gradient(135deg, #6366f1, #8b5cf6)', max_length=100)),
                ('languages_supported', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_definitions',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('objective', models.TextField()),
                ('instructions', models.TextField()),
                ('initial_state', models.JSONField(default=dict)),
                ('solution_criteria', models.JSONField(default=dict)),
                ('hints', models.JSONField(default=list)),
                ('code_snippets', models.JSONField(default=dict)),
                ('xp_reward', models.IntegerField(default=50)),
                ('perfect_bonus_xp', models.IntegerField(default=25)),
                ('no_hint_bonus_xp', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='gamification.gamedefinition')),
            ],
            options={
                'db_table': 'game_levels',
                'ordering': ['game', 'level_number'],
                'unique_together': {('game', 'level_number')},
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('TOTAL_XP', 'Total XP Reached'), ('CHALLENGES_COMPLETED', 'Challenges Completed'), ('QUIZZES_COMPLETED', 'Quizzes Completed'), ('LESSONS_COMPLETED', 'Lessons Completed'), ('STREAK_DAYS', 'Day Streak'), ('PERFECT_QUIZ', 'Perfect Quiz Score'), ('COMPETITION_WIN', 'Competition Win'), ('CODE_QUALITY', 'Code Quality Score'), ('FIRST_SUBMISSION', 'First Submission'), ('FIRST_QUIZ', 'First Quiz'), ('GAMES_COMPLETED', 'Games Completed'), ('GAME_PERFECT', 'Perfect Game Solution'), ('NO_HINT_GAMES', 'Games Without Hints')], max_length=30),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='source',
            field=models.CharField(choices=[('LESSON', 'Lesson Completed'), ('QUIZ', 'Quiz Passed'), ('CHALLENGE', 'Coding Challenge'), ('COMPETITION', 'Competition'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK', 'Daily Streak'), ('CODE_QUALITY', 'High Code Quality'), ('REWARD_SPENT', 'Reward Purchase'), ('MANUAL', 'Manual Award'), ('GAME', 'Code Logic Game')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyCodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('level_config', models.JSONField(default=dict)),
                ('target_concept', models.CharField(default='Logic & Control Flow', max_length=100)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('xp_reward', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='gamification.gamedefinition')),
            ],
            options={
                'db_table': 'daily_code_challenges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_level_unlocked', models.IntegerField(default=1)),
                ('levels_completed_count', models.IntegerField(default=0)),
                ('total_play_time_seconds', models.IntegerField(default=0)),
                ('total_xp_earned', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_mistakes', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=100.0)),
                ('adaptive_difficulty', models.CharField(default='BEGINNER', max_length=20)),
                ('weak_concepts', models.JSONField(default=list)),
                ('mastered_concepts', models.JSONField(default=list)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stats', to='gamification.gamedefinition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_game_stats',
                'unique_together': {('student', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='BEGINNER', max_length=20)),
                ('language_mode', models.CharField(default='python', max_length=30)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('attempts', models.IntegerField(default=1)),
                ('mistakes_count', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=100.0)),
                ('steps_executed', models.IntegerField(default=0)),
                ('optimal_steps', models.IntegerField(default=0)),
                ('efficiency_score', models.FloatField(default=100.0)),
                ('score', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('is_perfect', models.BooleanField(default=False)),
                ('concepts_tested', models.JSONField(default=list)),
                ('mistake_log', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_recommended_difficulty', models.CharField(default='BEGINNER', max_length=20)),
                ('ai_recommended_actions', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gamification.gamedefinition')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='gamification.gamelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'game', '-started_at'], name='game_sessio_student_b4bf56_idx'), models.Index(fields=['status', '-started_at'], name='game_sessio_status_30b632_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('xp_awarded', models.IntegerField(default=100)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='gamification.dailycodechallenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_challenge_completions',
                'unique_together': {('student', 'challenge')},
            },
        ),
    ]
