# Generated by Django 4.2.16 on 2026-08-31 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('XP_EARNED', 'XP Earned'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('LEVEL_UP', 'Level Up'), ('COMPETITION', 'Competition'), ('NEW_CHALLENGE', 'New Challenge'), ('RANK_CHANGE', 'Rank Changed'), ('AI_ANALYSIS', 'AI Analysis Ready'), ('TEACHER_FEEDBACK', 'Teacher Feedback'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('icon', models.CharField(default='🔔', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
